apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-depl
  namespace: wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
      annotations:
        kuma.io/mesh: default
    spec:
      containers:
        - name: generator
          image: ezegrosfeld/wallet-generator
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: '/health'
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: generator-srv
  namespace: wallet
spec:
  selector:
    app: generator
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
