name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'generator/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: cd generator && go build -v ./...

    - name: Test
      run: cd generator && go test ./... -covermode=atomic -coverpkg=./... -count=1 -race
    
    - name: Coverage
      run: bash <(curl -s https://codecov.io/bash)
